import type { PlaceTypeSearchInfo } from "./searchPoints.ts";

const uncommonPlaces: PlaceTypeSearchInfo[] = [
  // { placeType: "asian_grocery_store", searchRadius: 50000 },
  // { placeType: "island", searchRadius: 50000 },
  // { placeType: "woods", searchRadius: 50000 },
  // { placeType: "go_karting_venue", searchRadius: 50000 },
  // { placeType: "comedy_club", searchRadius: 50000 },
  // { placeType: "karaoke", searchRadius: 50000 },
  // { placeType: "planetarium", searchRadius: 50000 },
  // { placeType: "hindu_temple", searchRadius: 50000 },
  // { placeType: "mosque", searchRadius: 50000 },
  // { placeType: "synagogue", searchRadius: 50000 },
  // { placeType: "stadium", searchRadius: 50000 },
  // { placeType: "beach", searchRadius: 50000 },
  // { placeType: "zoo", searchRadius: 50000 },
  // { placeType: "aquarium", searchRadius: 50000 },
  // { placeType: "acai_shop", searchRadius: 50000 },
  // { placeType: "afghani_restaurant", searchRadius: 50000 },
  // { placeType: "african_restaurant", searchRadius: 50000 },
  // { placeType: "argentinian_restaurant", searchRadius: 50000 },
  // { placeType: "australian_restaurant", searchRadius: 50000 },
  // { placeType: "austrian_restaurant", searchRadius: 50000 },
  // { placeType: "bangladeshi_restaurant", searchRadius: 50000 },
  // { placeType: "basque_restaurant", searchRadius: 50000 },
  // { placeType: "bavarian_restaurant", searchRadius: 50000 },
  // { placeType: "belgian_restaurant", searchRadius: 50000 },
  // { placeType: "bistro", searchRadius: 50000 },
  // { placeType: "british_restaurant", searchRadius: 50000 },
  // { placeType: "burmese_restaurant", searchRadius: 50000 },
  // { placeType: "cafeteria", searchRadius: 50000 },
  // { placeType: "cajun_restaurant", searchRadius: 50000 },
  // { placeType: "californian_restaurant", searchRadius: 50000 },
  // { placeType: "cambodian_restaurant", searchRadius: 50000 },
  // { placeType: "cantonese_restaurant", searchRadius: 50000 },
  // { placeType: "caribbean_restaurant", searchRadius: 50000 },
  // { placeType: "chilean_restaurant", searchRadius: 50000 },
  // { placeType: "chinese_noodle_restaurant", searchRadius: 50000 },
  // { placeType: "chocolate_factory", searchRadius: 50000 },
  // { placeType: "colombian_restaurant", searchRadius: 50000 },
  // { placeType: "croatian_restaurant", searchRadius: 50000 },
  // { placeType: "cuban_restaurant", searchRadius: 50000 },
  // { placeType: "czech_restaurant", searchRadius: 50000 },
  // { placeType: "danish_restaurant", searchRadius: 50000 },
  // { placeType: "dim_sum_restaurant", searchRadius: 50000 },
  // { placeType: "dumpling_restaurant", searchRadius: 50000 },
  // { placeType: "dutch_restaurant", searchRadius: 50000 },
  // { placeType: "eastern_european_restaurant", searchRadius: 50000 },
  // { placeType: "ethiopian_restaurant", searchRadius: 50000 },
  // { placeType: "european_restaurant", searchRadius: 50000 },
  // { placeType: "falafel_restaurant", searchRadius: 50000 },
  // { placeType: "filipino_restaurant", searchRadius: 50000 },
  // { placeType: "fondue_restaurant", searchRadius: 50000 },
  // { placeType: "french_restaurant", searchRadius: 50000 },
  // { placeType: "german_restaurant", searchRadius: 50000 },
  // { placeType: "gyro_restaurant", searchRadius: 50000 },
  // { placeType: "hot_pot_restaurant", searchRadius: 50000 },
  // { placeType: "hungarian_restaurant", searchRadius: 50000 },
  // { placeType: "indonesian_restaurant", searchRadius: 50000 },
  // { placeType: "irish_restaurant", searchRadius: 50000 },
  // { placeType: "israeli_restaurant", searchRadius: 50000 },
  // { placeType: "japanese_curry_restaurant", searchRadius: 50000 },
  // { placeType: "japanese_izakaya_restaurant", searchRadius: 50000 },
  // { placeType: "kebab_shop", searchRadius: 50000 },
  // { placeType: "korean_barbecue_restaurant", searchRadius: 50000 },
  // { placeType: "lebanese_restaurant", searchRadius: 50000 },
  // { placeType: "malaysian_restaurant", searchRadius: 50000 },
  // { placeType: "mongolian_barbecue_restaurant", searchRadius: 50000 },
  // { placeType: "moroccan_restaurant", searchRadius: 50000 },
  // { placeType: "north_indian_restaurant", searchRadius: 50000 },
  // { placeType: "oyster_bar_restaurant", searchRadius: 50000 },
  // { placeType: "pakistani_restaurant", searchRadius: 50000 },
  // { placeType: "persian_restaurant", searchRadius: 50000 },
  // { placeType: "peruvian_restaurant", searchRadius: 50000 },
  // { placeType: "polish_restaurant", searchRadius: 50000 },
  // { placeType: "portuguese_restaurant", searchRadius: 50000 },
  // { placeType: "romanian_restaurant", searchRadius: 50000 },
  // { placeType: "russian_restaurant", searchRadius: 50000 },
  // { placeType: "scandinavian_restaurant", searchRadius: 50000 },
  // { placeType: "shawarma_restaurant", searchRadius: 50000 },
  // { placeType: "soul_food_restaurant", searchRadius: 50000 },
  // { placeType: "south_american_restaurant", searchRadius: 50000 },
  // { placeType: "south_indian_restaurant", searchRadius: 50000 },
  // { placeType: "southwestern_us_restaurant", searchRadius: 50000 },
  // { placeType: "spanish_restaurant", searchRadius: 50000 },
  // { placeType: "sri_lankan_restaurant", searchRadius: 50000 },
  // { placeType: "swiss_restaurant", searchRadius: 50000 },
  // { placeType: "taiwanese_restaurant", searchRadius: 50000 },
  // { placeType: "tapas_restaurant", searchRadius: 50000 },
  // { placeType: "tibetan_restaurant", searchRadius: 50000 },
  // { placeType: "tonkatsu_restaurant", searchRadius: 50000 },
  // { placeType: "turkish_restaurant", searchRadius: 50000 },
  // { placeType: "ukrainian_restaurant", searchRadius: 50000 },
  // { placeType: "western_restaurant", searchRadius: 50000 },
  // { placeType: "winery", searchRadius: 50000 },
  // { placeType: "yakiniku_restaurant", searchRadius: 50000 },
  // { placeType: "yakitori_restaurant", searchRadius: 50000 },
  // { placeType: "discount_supermarket", searchRadius: 50000 },
  // { placeType: "farmers_market", searchRadius: 50000 },
  // { placeType: "flea_market", searchRadius: 50000 },
  // { placeType: "general_store", searchRadius: 50000 },
  // { placeType: "hypermarket", searchRadius: 50000 },
  // { placeType: "arena", searchRadius: 50000 },
  // { placeType: "fishing_pier", searchRadius: 50000 },
  // { placeType: "ice_skating_rink", searchRadius: 50000 },
];

export const slcSearches: PlaceTypeSearchInfo[] = [
  ...uncommonPlaces,
  // { placeType: "fishing_charter", searchRadius: 40000 },
  // { placeType: "race_course", searchRadius: 40000 },
  // { placeType: "scenic_spot", searchRadius: 40000 },
  // { placeType: "cake_shop", searchRadius: 40000 },
  // { placeType: "video_arcade", searchRadius: 20000 },
  // { placeType: "halal_restaurant", searchRadius: 20000 },
  // { placeType: "ski_resort", searchRadius: 20000 },
  // { placeType: "noodle_shop", searchRadius: 20000 },
  // { placeType: "nature_preserve", searchRadius: 16000 },
  // { placeType: "middle_eastern_restaurant", searchRadius: 15000 },
  // { placeType: "greek_restaurant", searchRadius: 8000 },
  // { placeType: "movie_theater", searchRadius: 8000 },
  // { placeType: "golf_course", searchRadius: 8000 },
  // { placeType: "department_store", searchRadius: 8000 },
  // { placeType: "campground", searchRadius: 8000 },
  // { placeType: "indoor_golf_course", searchRadius: 7000 },
  // { placeType: "supermarket", searchRadius: 5000 },
  // { placeType: "sports_coaching", searchRadius: 5000 },
  // { placeType: "hiking_area", searchRadius: 4000 },
  // { placeType: "swimming_pool", searchRadius: 4000 },
  // { placeType: "shopping_mall", searchRadius: 4000 },
  // { placeType: "playground", searchRadius: 3000 },
  // { placeType: "tennis_court", searchRadius: 3000 },
  // { placeType: "library", searchRadius: 2000 },
  // { placeType: "museum", searchRadius: 2000 },
  // { placeType: "book_store", searchRadius: 1200 },
  // { placeType: "sports_club", searchRadius: 1200 },
  // { placeType: "tourist_attraction", searchRadius: 1000 },
  // { placeType: "grocery_store", searchRadius: 1000 },
  // { placeType: "park", searchRadius: 1000 },
  // { placeType: "athletic_field", searchRadius: 1000 },
  // { placeType: "fitness_center", searchRadius: 1000 },
  // { placeType: "sports_complex", searchRadius: 1000 },
  // { placeType: "sports_school", searchRadius: 1000 },
  // { placeType: "gym", searchRadius: 900 },
  // { placeType: "cafe", searchRadius: 500 },
  // { placeType: "bakery", searchRadius: 500 },
  // { placeType: "meal_takeaway", searchRadius: 500 },
  // { placeType: "church", searchRadius: 500 },
  // { placeType: "clothing_store", searchRadius: 500 },
  // { placeType: "restaurant", searchRadius: 200 },
  // { placeType: "store", searchRadius: 150 },
  // { placeType: "sports_activity_location", searchRadius: 500 },
];

export const provoSearches: PlaceTypeSearchInfo[] = [
  ...uncommonPlaces,
  { placeType: "fishing_pond", searchRadius: 49000 },
  { placeType: "fishing_charter", searchRadius: 40000 },
  { placeType: "race_course", searchRadius: 40000 },
  { placeType: "scenic_spot", searchRadius: 40000 },
  { placeType: "nature_preserve", searchRadius: 40000 },
  { placeType: "ski_resort", searchRadius: 30000 },
  { placeType: "river", searchRadius: 20000 },
  { placeType: "indoor_golf_course", searchRadius: 10000 },
  { placeType: "mountain_peak", searchRadius: 10000 },
  { placeType: "garden_center", searchRadius: 10000 },
  { placeType: "sportswear_store", searchRadius: 10000 },
  { placeType: "supermarket", searchRadius: 10000 },
  { placeType: "thrift_store", searchRadius: 10000 },
  { placeType: "library", searchRadius: 8000 },
  { placeType: "supermarket", searchRadius: 8000 },
  { placeType: "movie_theater", searchRadius: 8000 },
  { placeType: "golf_course", searchRadius: 8000 },
  { placeType: "department_store", searchRadius: 8000 },
  { placeType: "campground", searchRadius: 8000 },
  { placeType: "sports_coaching", searchRadius: 7000 },
  { placeType: "fitness_center", searchRadius: 5000 },
  { placeType: "playground", searchRadius: 5000 },
  { placeType: "tennis_court", searchRadius: 5000 },
  { placeType: "toy_store", searchRadius: 5000 },
  { placeType: "pet_store", searchRadius: 5000 },
  { placeType: "museum", searchRadius: 4000 },
  { placeType: "book_store", searchRadius: 4000 },
  { placeType: "swimming_pool", searchRadius: 4000 },
  { placeType: "shopping_mall", searchRadius: 4000 },
  { placeType: "sports_club", searchRadius: 4000 },
  { placeType: "cell_phone_store", searchRadius: 3000 },
  { placeType: "athletic_field", searchRadius: 3000 },
  { placeType: "sports_school", searchRadius: 3000 },
  { placeType: "discount_store", searchRadius: 3000 },
  { placeType: "gift_shop", searchRadius: 3000 },
  { placeType: "grocery_store", searchRadius: 3000 },
  { placeType: "shoe_store", searchRadius: 3000 },
  { placeType: "gym", searchRadius: 3000 },
  { placeType: "lake", searchRadius: 2500 },
  { placeType: "sports_complex", searchRadius: 2000 },
  { placeType: "tourist_attraction", searchRadius: 2000 },
  { placeType: "cafe", searchRadius: 1600 },
  { placeType: "sports_activity_location", searchRadius: 1000 },
  { placeType: "jewelry_store", searchRadius: 1000 },
  { placeType: "sporting_goods_store", searchRadius: 1000 },
  { placeType: "wholesaler", searchRadius: 1000 },
  { placeType: "park", searchRadius: 1000 },
  { placeType: "bakery", searchRadius: 1000 },
  { placeType: "meal_takeaway", searchRadius: 1000 },
  { placeType: "grocery_store", searchRadius: 1000 },
  { placeType: "church", searchRadius: 500 },
  { placeType: "clothing_store", searchRadius: 500 },
  { placeType: "restaurant", searchRadius: 300 },
  { placeType: "store", searchRadius: 150 },
];

export const lehiSearches: PlaceTypeSearchInfo[] = [
  // { placeType: "video_arcade", searchRadius: 20000 },
  // { placeType: "movie_theater", searchRadius: 15000 },
  // { placeType: "amusement_park", searchRadius: 15000 },
  // { placeType: "supermarket", searchRadius: 15000 },
  // { placeType: "department_store", searchRadius: 15000 },
  // { placeType: "shopping_mall", searchRadius: 15000 },
  // { placeType: "museum", searchRadius: 12000 },
  // { placeType: "library", searchRadius: 12000 },
  // { placeType: "hiking_area", searchRadius: 7000 },
  // { placeType: "golf_course", searchRadius: 9000 },
  // { placeType: "campground", searchRadius: 8000 },
  // { placeType: "tourist_attraction", searchRadius: 4500 },
  // { placeType: "swimming_pool", searchRadius: 4500 },
  // { placeType: "book_store", searchRadius: 4000 },
  // { placeType: "cafe", searchRadius: 4000 },
  // { placeType: "grocery_store", searchRadius: 4000 },
  // { placeType: "meal_takeaway", searchRadius: 3000 },
  // { placeType: "sports_club", searchRadius: 2000 },
  // { placeType: "gym", searchRadius: 2000 },
  // { placeType: "park", searchRadius: 2000 },
  // { placeType: "bakery", searchRadius: 2000 },
  // { placeType: "clothing_store", searchRadius: 2000 },
  // { placeType: "church", searchRadius: 1000 },
  // { placeType: "restaurant", searchRadius: 1000 },
  // { placeType: "store", searchRadius: 300 },
];

export const lindonSearches: PlaceTypeSearchInfo[] = [
  // { placeType: "library", searchRadius: 8000 },
  // { placeType: "supermarket", searchRadius: 8000 },
  // { placeType: "movie_theater", searchRadius: 8000 },
  // { placeType: "golf_course", searchRadius: 8000 },
  // { placeType: "department_store", searchRadius: 8000 },
  // { placeType: "campground", searchRadius: 8000 },
  // { placeType: "museum", searchRadius: 8000 },
  // { placeType: "book_store", searchRadius: 8000 },
  // { placeType: "swimming_pool", searchRadius: 8000 },
  // { placeType: "shopping_mall", searchRadius: 8000 },
  // { placeType: "hiking_area", searchRadius: 5000 },
  // { placeType: "grocery_store", searchRadius: 4000 },
  // { placeType: "sports_club", searchRadius: 4000 },
  // { placeType: "tourist_attraction", searchRadius: 4000 },
  // { placeType: "cafe", searchRadius: 4000 },
  // { placeType: "meal_takeaway", searchRadius: 3000 },
  // { placeType: "bakery", searchRadius: 3000 },
  // { placeType: "gym", searchRadius: 2400 },
  // { placeType: "park", searchRadius: 2000 },
  // { placeType: "church", searchRadius: 2000 },
  // { placeType: "clothing_store", searchRadius: 2000 },
  // { placeType: "restaurant", searchRadius: 1000 },
  // { placeType: "store", searchRadius: 500 },
];

export const hayesParkSearches: PlaceTypeSearchInfo[] = [
  // { placeType: "library", searchRadius: 8000 },
  // { placeType: "supermarket", searchRadius: 8000 },
  // { placeType: "movie_theater", searchRadius: 8000 },
  // { placeType: "golf_course", searchRadius: 8000 },
  // { placeType: "department_store", searchRadius: 8000 },
  // { placeType: "campground", searchRadius: 8000 },
  // { placeType: "museum", searchRadius: 8000 },
  // { placeType: "book_store", searchRadius: 8000 },
  // { placeType: "swimming_pool", searchRadius: 8000 },
  // { placeType: "shopping_mall", searchRadius: 8000 },
  // { placeType: "hiking_area", searchRadius: 5000 },
  // { placeType: "grocery_store", searchRadius: 6000 },
  // { placeType: "sports_club", searchRadius: 6000 },
  // { placeType: "cafe", searchRadius: 6000 },
  // { placeType: "gym", searchRadius: 5000 },
  // { placeType: "tourist_attraction", searchRadius: 5000 },
  // { placeType: "bakery", searchRadius: 5000 },
  // { placeType: "meal_takeaway", searchRadius: 5000 },
  // { placeType: "clothing_store", searchRadius: 4000 },
  // { placeType: "church", searchRadius: 2000 },
  // { placeType: "park", searchRadius: 2000 },
  // { placeType: "restaurant", searchRadius: 2000 },
  // { placeType: "store", searchRadius: 1000 },
];
