const placeTypes: string[] = [
  "tourist_attraction",
  "museum",
  "library",
  "movie_theater",
  "amusement_park",
  "zoo",
  "aquarium",
  "park",
  "campground",
  "beach",
  "restaurant",
  "cafe",
  "bar",
  "bakery",
  "meal_takeaway",
  "store",
  "shopping_mall",
  "supermarket",
  "department_store",
  "grocery_store",
  "book_store",
  "clothing_store",
  "sports_club",
  "gym",
  "golf_course",
  "swimming_pool",
  "stadium",
  "church",
  "hindu_temple",
  "mosque",
  "synagogue",
]

module.exports = placeTypes
